### ISSUE TITLE
Bug in whitelist feature

### ISSUE THREAD

**Issue by Quik2007** [xGoldenK/CustomTabCompleter#1]
Hey there, if you turn on whitelist as well as fake_no_permission_when_using_blacklisted_command, the plugin will send the fake permission message if the command is not exactly in the whitelist -> Arguments do not work.

Example:
fake_no_permission_when_using_blacklisted_command: true
whitelist_instead_of_blacklist: true
blacklisted_commands:
- msg
fake_no_permission_message: Unknown command. Type "/help" for help.

The players won't be able to use /msg Someone Some message, because the full command text is used to check if it is in the whitelist and not the command itself.

**Comment by xGoldenK** [comment]
Fixed in the latest update!
Thank you.
